export const TRANSACTION_CATEGORIES = [
  { id: 0, name: "Groceries", icon: "🛒" },
  { id: 1, name: "Dining & Restaurants", icon: "🍽️" },
  { id: 2, name: "Transportation", icon: "🚗" },
  { id: 3, name: "Gas & Fuel", icon: "⛽" },
  { id: 4, name: "Utilities", icon: "💡" },
  { id: 5, name: "Rent & Mortgage", icon: "🏠" },
  { id: 6, name: "Insurance", icon: "🛡️" },
  { id: 7, name: "Healthcare & Medical", icon: "🏥" },
  { id: 8, name: "Fitness & Gym", icon: "💪" },
  { id: 9, name: "Shopping & Retail", icon: "🛍️" },
  { id: 10, name: "Entertainment", icon: "🎬" },
  { id: 11, name: "Subscriptions", icon: "📱" },
  { id: 12, name: "Education", icon: "📚" },
  { id: 13, name: "Travel", icon: "✈️" },
  { id: 14, name: "Hotels & Lodging", icon: "🏨" },
  { id: 15, name: "Personal Care", icon: "💅" },
  { id: 16, name: "Phone & Internet", icon: "📞" },
  { id: 17, name: "Streaming Services", icon: "📺" },
  { id: 18, name: "Coffee Shops", icon: "☕" },
  { id: 19, name: "Fast Food", icon: "🍔" },
  { id: 20, name: "Clothing & Apparel", icon: "👕" },
  { id: 21, name: "Electronics", icon: "💻" },
  { id: 22, name: "Home Improvement", icon: "🔨" },
  { id: 23, name: "Furniture", icon: "🛋️" },
  { id: 24, name: "Pet Care", icon: "🐾" },
  { id: 25, name: "Childcare", icon: "👶" },
  { id: 26, name: "Gifts & Donations", icon: "🎁" },
  { id: 27, name: "Charity", icon: "❤️" },
  { id: 28, name: "Savings & Investments", icon: "💰" },
  { id: 29, name: "Loan Payments", icon: "💳" },
  { id: 30, name: "Credit Card Payment", icon: "💳" },
  { id: 31, name: "Bank Fees", icon: "🏦" },
  { id: 32, name: "ATM Withdrawal", icon: "🏧" },
  { id: 33, name: "Transfer", icon: "💸" },
  { id: 34, name: "Refund", icon: "↩️" },
  { id: 35, name: "Salary & Income", icon: "💵" },
  { id: 36, name: "Freelance Income", icon: "💼" },
  { id: 37, name: "Investment Income", icon: "📈" },
  { id: 38, name: "Books & Magazines", icon: "📖" },
  { id: 39, name: "Hobbies", icon: "🎨" },
  { id: 40, name: "Sports & Recreation", icon: "⚽" },
  { id: 41, name: "Alcohol & Bars", icon: "🍺" },
  { id: 42, name: "Tobacco", icon: "🚬" },
  { id: 43, name: "Parking", icon: "🅿️" },
  { id: 44, name: "Tolls", icon: "🛣️" },
  { id: 45, name: "Public Transit", icon: "🚇" },
  { id: 46, name: "Ride Share", icon: "🚕" },
  { id: 47, name: "Taxes", icon: "📄" },
  { id: 48, name: "Legal Services", icon: "⚖️" },
  { id: 49, name: "Accounting & Financial", icon: "📊" },
  { id: 50, name: "Other", icon: "📦" },
] as const;

export type TransactionCategory = typeof TRANSACTION_CATEGORIES[number];